name: OpenSuse mingw CI (docker image)

on:
  release:
    types: [created]

jobs:

  docker_publish:
    name: Docker build image publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        openfoam_version: [v2206]

    steps:
    
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v1.1.2
      with:
        files: |
          docker/opensuse-mingw
          .github/workflows/opensuse-mingw.yml
          
    - name: Log in to the Container registry
      if: steps.changed-files.outputs.modified_files != ''
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push to GitHub Packages ${{matrix.openfoam_version}}
      if: steps.changed-files.outputs.modified_files != ''
      uses: docker/build-push-action@v1
      with:
        registry: ghcr.io
        tags: openfoam-${{matrix.openfoam_version}}-opensuse-mingw
        dockerfile: docker/opensuse-mingw
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        build_args: OPENFOAM_BRANCH=OpenFOAM-${{matrix.openfoam_version}}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: docker_publish

    strategy:
      matrix:
        openfoam_version: [ v2206]

    container: 'ghcr.io/${{github.actor}}/porousmultiphasefoam:openfoam-${{matrix.openfoam_version}}-opensuse-mingw'

    steps:

    - uses: nelonoel/branch-name@v1.0.1

    - name: Checkout
      run: |
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git -b ${BRANCH_NAME} .

    - name: Build
      run: |
           FOAM_VERBOSE=true &&  source /openfoam/etc/bashrc /openfoam/etc-mingw/prefs.sh && ls && ./Allwmake -j
           zip -r pmf-opensuse-mingw-${{matrix.openfoam_version}}.zip /github/home/OpenFOAM/user-${{matrix.openfoam_version}}/platforms/linux64MingwDPInt32Opt/

    - name: Installer archive upload push
      uses: actions/upload-artifact@v3
      with:
          path: pmf-opensuse-mingw-${{matrix.openfoam_version}}.zip

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3

    - name: Publish assets
      uses: alexellis/upload-assets@0.4.0
      env:
          GITHUB_TOKEN: ${{ github.token }}
      with:
          asset_paths: '["*/*.zip"]'